# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akord', '0002_zdjecie_obraz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdjecie',
            name='obraz',
            field=models.ImageField(upload_to='media/zdjecia/'),
        ),
    ]
