# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('akord', '0003_auto_20170806_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wideo',
            name='link',
        ),
        migrations.AddField(
            model_name='wideo',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
        migrations.AlterField(
            model_name='zdjecie',
            name='obraz',
            field=models.ImageField(upload_to='zdjecia/'),
        ),
    ]
