# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akord', '0006_auto_20170817_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wideo',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
