# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akord', '0008_auto_20170817_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriaPiosenki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_ketegori', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfiloweD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obraz', models.ImageField(upload_to='zdjecia/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfiloweL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obraz', models.ImageField(upload_to='zdjecia/')),
            ],
        ),
        migrations.AlterField(
            model_name='wideo',
            name='url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='piosenka',
            name='kategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='akord.KategoriaPiosenki'),
        ),
    ]
