# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akord', '0009_auto_20170924_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='wideo',
            name='tytul',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
